---
- hosts: all 
  become: yes 
  tasks: 
  - name: installing linux audit
    apt: 
      name: auditd
      state: latest
      update_cache: true

  - name: Installing AFL++
    apt:
      name: afl++
      state: latest 
      update_cache: true

  - name: installing lib-audit, lib-auparse and pyhton3-audit, cmake
    apt: 
      name: 
        - libaudit-dev
        - libauparse-dev
        - python3-audit
        - libseccomp-dev
        - cmake
        - python3-pip
        - bpfcc-tools
      state: latest 
      update_cache: true

  - name: compiling and moving the syscallFinder plugin 
    ansible.builtin.shell: sudo  gcc {{lookup('env', 'GIT_REPO')}}/syscall_finder_plugin/audisp-plugin.c -o /usr/local/sbin/sbp-audisp-plugin -laudit -lauparse
  
  - name: Executing CMake for File-Finder src 
    ansible.builtin.shell: sudo cmake {{lookup('env', 'GIT_REPO')}}/fileFinder -B {{lookup('env', 'GIT_REPO')}}/fileFinder

  - name: Compiling File-Finder src 
    ansible.builtin.shell: sudo make -C {{lookup('env', 'GIT_REPO')}}/fileFinder

  - name: installing the file finder plugin 
    ansible.builtin.shell: sudo python3 {{lookup('env', 'GIT_REPO')}}/fileFinder/installConfigFile.py {{lookup('env', 'GIT_REPO')}}/fileFinder/AudispPlugin

  - name: Changing configuration of the file finder plugin 
    ansible.builtin.file: 
      path: /etc/audit/plugins.d/AudispPlugin.conf
      owner: root
      group: root 
      mode: '0640'

  - name: moving config for syscall_finder 
    ansible.builtin.shell: sudo cp {{lookup('env', 'GIT_REPO')}}/syscall_finder_plugin/syscall_finder_config/sbp.conf /etc/audit/plugins.d/

  - name: Setting config file permission accordingly
    file: /etc/audit/plugins.d/sbp.conf mode=g-w,o-r
    file: 
      path: /etc/audit/plugins.d/sbp.conf
      owner: root
      group: root 

  - name: Marking the fuzzing plugin as executable
    ansible.builtin.file: 
      path: "{{lookup('env', 'GIT_REPO')}}/audisp_plugins/fuzzing_plugin.py"
      owner: root 
      group: root 
      mode: '0755'
  - name: moving plugin for fuzzing
    ansible.builtin.shell: sudo cp {{lookup('env', 'GIT_REPO')}}/audisp_plugins/fuzzing_plugin.py /usr/local/sbin/fuzzing_plugin.py

  - name: Marking the seccomp plugin as executable
    ansible.builtin.file: 
      path: "{{lookup('env', 'GIT_REPO')}}/audisp_plugins/syscall_logger.py" 
      owner: root 
      group: root 
      mode: '0755'

  - name: moving plugin for seccomp filtering 
    ansible.builtin.shell:  sudo cp {{lookup('env', 'GIT_REPO')}}/audisp_plugins/syscall_logger.py  /usr/local/sbin/syscall_logger.py

  - name: Create Fuzzing Output Dir
    file:
      path: /fuzzing/out
      state: directory

  - name: Create Fuzzing Input Dir
    file:
      path: /fuzzing/in
      state: directory

  - name: Replacing Priority Boost Auditd
    lineinfile: 
      path: /etc/audit/auditd.conf
      regexp: '^(.*)priority_boost =(.*)$' 
      line: 'priority_boost = 10'
      backrefs: yes

  - name: Increasing Auditd Queue Depth
    lineinfile: 
      path: /etc/audit/auditd.conf
      regexp: '^(.*)q_depth =(.*)$' 
      line: 'q_depth = 1000'
      backrefs: yes

  - name: installing Bubblewrap
    apt: 
      name: 
        - bubblewrap
      state: latest 
      update_cache: true
  
  - name: Change permission of GLIBC installation script
    file: dest={{lookup('env', 'GIT_REPO')}}/customGLIBC/custom_glibc_install.sh mode=a+x 
  
  - name: executing GLIBC installation script 
    shell: 
      cmd: ./custom_glibc_install.sh
      chdir: "{{lookup('env', 'GIT_REPO')}}/customGLIBC"