0 = "read"
1 = "write"
3 = "close"
4 = "stat"
6 = "lstat"
8 = "lseek"
9 = "mmap"
10 = "mprotect"
11 = "munmap"
12 = "brk"
13 = "rt_sigaction"
16 = "ioctl"
17 = "pread64"
21 = "access"
22 = "pipe"
33 = "dup2"
56 = "clone"
59 = "execve"
61 = "wait4"
72 = "fcntl"
131 = "sigaltstack"
158 = "arch_prctl"
231 = "exit_group"
257 = "openat"
262 = "newfstatat"
