0 = "read"
1 = "write"
3 = "close"
4 = "stat"
5 = "fstat"
6 = "lstat"
8 = "lseek"
9 = "mmap"
10 = "mprotect"
11 = "munmap"
12 = "brk"
13 = "rt_sigaction"
16 = "ioctl"
17 = "pread64"
21 = "access"
22 = "pipe"
25 = "mremap"
33 = "dup2"
58 = "vfork"
59 = "execve"
61 = "wait4"
157 = "prctl"
158 = "arch_prctl"
217 = "getdents64"
231 = "exit_group"
257 = "openat"
262 = "newfstatat"
280 = "utimensat"
317 = "seccomp"
