0 = "read"
1 = "write"
3 = "close"
8 = "lseek"
9 = "mmap"
10 = "mprotect"
11 = "munmap"
12 = "brk"
13 = "rt_sigaction"
14 = "rt_sigprocmask"
16 = "ioctl"
17 = "pread64"
21 = "access"
41 = "socket"
42 = "connect"
63 = "uname"
79 = "getcwd"
89 = "readlink"
125 = "capget"
137 = "statfs"
157 = "prctl"
158 = "arch_prctl"
191 = "getxattr"
192 = "lgetxattr"
202 = "futex"
217 = "getdents64"
218 = "set_tid_address"
231 = "exit_group"
257 = "openat"
262 = "newfstatat"
273 = "set_robust_list"
302 = "prlimit64"
332 = "statx"
