0 = "read"
1 = "write"
3 = "close"
8 = "lseek"
9 = "mmap"
10 = "mprotect"
11 = "munmap"
12 = "brk"
13 = "rt_sigaction"
14 = "rt_sigprocmask"
15 = "rt_sigreturn"
16 = "ioctl"
17 = "pread64"
20 = "writev"
25 = "mremap"
27 = "mincore"
28 = "madvise"
33 = "dup2"
39 = "getpid"
56 = "clone"
59 = "execve"
60 = "exit"
61 = "wait4"
72 = "fcntl"
79 = "getcwd"
89 = "readlink"
96 = "gettimeofday"
99 = "sysinfo"
131 = "sigaltstack"
143 = "sched_getparam"
144 = "sched_setscheduler"
145 = "sched_getscheduler"
146 = "sched_get_priority_max"
147 = "sched_get_priority_min"
186 = "gettid"
201 = "time"
202 = "futex"
204 = "sched_getaffinity"
217 = "getdents64"
228 = "clock_gettime"
231 = "exit_group"
234 = "tgkill"
257 = "openat"
262 = "newfstatat"
273 = "set_robust_list"
293 = "pipe2"
302 = "prlimit64"
318 = "getrandom"
